import Head from "next/head";
import styles from "@/styles/Home.module.css";
import ARBETH from "@/components/ARBETH/ARBETH";

export default function Home() {
  return (
    <>
      <Head>
        <title>ARB/ETH MAKER ORDERS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ARBETH />
    </>
  );
}
