import Head from "next/head";
import styles from "@/styles/Home.module.css";
import GDXWETH from "@/components/GDXWETH/GDXWETH";
import { Heading } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>GDX/WETH MAKER ORDERS IN BATCH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GDXWETH />
    </>
  );
}
