import Head from "next/head";
import styles from "@/styles/Home.module.css";
import GDXETH from "@/components/GDXETH/GDXETH";
import { Heading } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>GDX/ETH MAKER ORDERS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GDXETH />
    </>
  );
}
